### ISSUE TITLE
Duplicate Gas Stations

### ISSUE THREAD

**Issue by joluet** [fuel-me-up/fuel-me-up-server#1]
Some gas stations are provided by the car2go as well as the drive-now api. But the coordinates may differ slightly. These duplicates may confuse the user. To avoid this the fuel-me-up server should merge gas stations when the distance between them is below a certain threshold.

**Comment by mAu888** [comment]
This is actually done here: https://github.com/fuel-me-up/fuel-me-up-server/blob/f435c794189f508475b71058f79c7b58284da572/crawler/gasstations/gasstations-crawler.js#L54-L64
